import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  other: {
    'theme-color': "#0d1117",
    "color-scheme": "dark only",
    "twitter_image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Ftest%2520pattern%2F&psig=AOvVaw2W3C4hvJkQRszoX0KI0HDt&ust=1704457179655000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCJCwsvjbw4MDFQAAAAAdAAAAABAD",
    "twitter:card": "sumarry_large_image",
    "og:url": 'commpasevent.no',
    "og:image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Ftest%2520pattern%2F&psig=AOvVaw2W3C4hvJkQRszoX0KI0HDt&ust=1704457179655000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCJCwsvjbw4MDFQAAAAAdAAAAABAD",
    "og:type": "website",
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex place-content-center`}>
        <div className='bg-black max-w-7xl w-full'>
          {children}
        </div>
      </body>
    </html>
  )
}